name: mindbox
description: Mindbox SDK.
version: 0.0.1
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-moscow/flutter-sdk/tree/master/mindbox
issue_tracker:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mindbox_android
      ios:
        default_package: mindbox_ios

dependencies:
  flutter:
    sdk: flutter
  mindbox_android:
    git:
      url: https://github.com/mindbox-moscow/flutter-sdk
      ref: pushok-test
      path: mindbox_android
  mindbox_ios:
    git:
      url: https://github.com/mindbox-moscow/flutter-sdk
      ref: pushok-test
      path:  mindbox_ios
  mindbox_platform_interface:
    git:
      url: https://github.com/mindbox-moscow/flutter-sdk
      ref: pushok-test
      path: mindbox_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4